#ifndef _DEFINES_H_
#define _DEFINES_H_

#define SCORE_OFFSET_X  50
#define SCORE_OFFSET_Y  50
#define LEVEL_OFFSET_X  931
#define LEVEL_OFFSET_Y  631
#define BUBBLE_OFFSET_X 285
#define BUBBLE_OFFSET_Y 105
#define BUBBLE_WIDTH    40
#define BUBBLE_HEIGHT   40
#define NUM_BUBBLES     5
#define NUM_LEVELS      7
#define BOARD_SIZE_X    10
#define BOARD_SIZE_Y    10

#define CANNON_BUBBLE_OFFSET_X  30
#define CANNON_BUBBLE_OFFSET_Y 640
#define CANNON_BUBBLE_WIDTH     65
#define CANNON_BUBBLE_HEIGHT    65

#define SPARE_BUBBLE_OFFSET_X 480
#define SPARE_BUFFLE_OFFSET_Y 650
#define SPARE_BUBBLE_W         50
#define SPARE_BUBBLE_H         50
#endif /* _DEFINES_H_ */