#ifndef BUBBLE_COLOR_H_
#define BUBBLE_COLOR_H_

enum BubbleColor
{
    BUBBLE_NONE = -1,
    BUBBLE_BLUE,
    BUBBLE_YELLOW,
    BUBBLE_GREEN,
    BUBBLE_RED,
    BUBBLE_TRANSPARENT
};

#endif // BUBBLE_COLOR_H_