#ifndef SOUND_TYPE_H_
#define SOUND_TYPE_H_

enum SoundType
{
    SOUND_SHOOT_BUBBLE,
    SOUND_FAILED_SHOT,
    SOUND_COMBO,
    SOUND_COMBO_BONUS1,
    SOUND_COMBO_BONUS2,
    SOUND_FULLY_LOADED,
    SOUND_HIT_WALL,
    SOUND_LEVEL_UP,
    SOUND_RESET_BONUS
};

#endif // SOUND_TYPE_H_